[package]
name = "stdweb_electron"
version = "0.1.0"
authors = ["Bradlee Speice <bradlee@speice.io>"]
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
stdweb = "0.4.20"
wasm-bindgen = "0.2"
